### PR TITLE
Agn sources

### PR DESCRIPTION
**Pull request by Henry-Best-01**
Small update to make random AGN have a randomly generated broken power law intrinsic signal. Before this, only a sinusoidal signal was provided. 

Also including int() for some previous integer division in astro_util.

### CODE REVIEW

**Comment by Henry-Best-01** [comment]
Also added a couple lines in agan_variability notebook.

**Comment by nkhadka21** [comment]
Hi @Henry-Best-01 , fyi, Pre-commit QA fail is from Precommit side. Hope, they will fix it soon. Currently, we ignore it.

**Comment by Henry-Best-01** [comment]
Previous failure which I labeled "random error in galaxy deflector test" seemed to be a completely random failure. Please look at the failure labeled 73ced4d . Perhaps there was a random number generated just outside the assertion window?

**Review by nkhadka21 — CHANGES_REQUESTED** [review]
Hi @Henry-Best-01 , thank you very much for this PR! It looks good to me. I have some minor comments on notebook. Please look at them.

**Comment by Henry-Best-01** [comment]
I left the last print statement associated with the griz bands, since the mean / deviation of these light curves is not directly apparent in the plot. I can remove them if you would like!

**Comment by nkhadka21** [comment]
Thank you very much @Henry-Best-01 for this PR! It looks good and I merge it.

**Pull request merged**
