### PR TITLE
Documentation update: Notebook tutorials

### PR DESCRIPTION
**Pull request by BrunoSanchez**
With these changes I included some of the notebooks (the ones I could locally run in my laptop at the moment) into the documentation.
Also attempted to fix your doc building problems (seems to be related to changes in `scipy.integrate` module, affecting `slsim` and `skypy`).

Please check with local build of the new docs that the "Tutorial" menu is available now, and that the files are correctly linked.

### CODE REVIEW

**Comment by sibirrer** [comment]
Thank you very much @BrunoSanchez ! This is super helpful. I let @nkhadka21 review it. Chances are that we do not need tutorials for all the notebooks (as it's hard to maintain working jupyter notebooks compared to python files, and the commits and changes become storage inefficient with figures)

**Comment by nkhadka21** [comment]
Hi @BrunoSanchez, thank you very much for this PR! This is very helpful. I noticed that codcov/project check is taking very long time. I am not sure what is causing this. @ajshajib might have idea about it!

**Comment by sibirrer** [comment]
> Hi @BrunoSanchez, thank you very much for this PR! This is very helpful. I noticed that codcov/project check is taking very long time. I am not sure what is causing this. @ajshajib might have idea about it!

@nkhadka21 it might be a glitch. It's not that code coverage should change with Bruno's PR

**Review by nkhadka21 — APPROVED** [review]
Hi @BrunoSanchez , thank you very much for this PR! It looks great.

**Pull request merged**
