### PR TITLE
Adding functionality for interpolated source: COSMOS real galaxy image test case

### PR DESCRIPTION
**Pull request by rahulmkarthik**
Made changes to source.py, lens.py to implement a test case for interpolated source from the COSMOS image catalog. Made sure the source, lens, and image_simulation tests were passing. Appears to be a problem with the actual image simulation, as the source isn't appearing.

### CODE REVIEW

**Comment by nkhadka21** [comment]
Hi @rahulmkarthik , thank you very much for this PR! Your branch has conflict with the main branch. Please resolved this conflict from your side. May be pulling main to your branch might resolved the conflict.

**Comment by rahulmkarthik** [comment]
> Hi @rahulmkarthik , thank you very much for this PR! Your branch has conflict with the main branch. Please resolved this conflict from your side. May be pulling main to your branch might resolved the conflict.

Hi Narayan. I've pulled main to my branch and made changes to remove the large COSMOS source FITS file from my fork, replacing it with the npy image used in the test case. Please let me know if there is still a conflict or if there is anything left to change from my end!

**Comment by sibirrer** [comment]
@rahulmkarthik you see that there is a conflict in this thread in three different files. There should be a conflict message when you pull the current main branch on the main repository into your main branch

**Comment by nkhadka21** [comment]
Hi @rahulmkarthik, If you have not resolved these conflicts, let me know. We can sit together and resolve these issue! thanks.

**Pull request closed without merging**
