### PR TITLE
Created Supernovae Population Overview Notebook

### PR DESCRIPTION
**Pull request by cmistick**
- Created overview notebook for the supernovae population which includes:
       - Number density calculations and plots
       - Lightcone integration
       - Host galaxy matching
       - Supernovae host offsets and plots
       - Corner plot and redshift distribution plot
       - Time series imaging

### CODE REVIEW

**Comment by nkhadka21** [comment]
Hi @cmistick , Thank you very much for this complete notebook! There is pre-commit fail. Please fix them!

**Comment by cmistick** [comment]
The offset plot in this notebook still needs to be updated after the offset PR is completed, but everything else should be up to date.

**Comment by cmistick** [comment]
PR is complete.

**Review by nkhadka21 — APPROVED** [review]
Hi @cmistick , thank you very much for this supernovae overview notebook! It looks great. I approve it.

**Pull request merged**
